#!/usr/bin/env bash

declare PREFIXES="${PREFIXES:-docker.rodeopartners.com/alpine}"
declare VERSIONS="${VERSIONS:-versions/*}"

declare version_files="${*:-$VERSIONS}"
: "${version_files:?}"

if [[ -z $(which docker) ]]; then
	echo "Missing docker client which is required for building"
	exit 2
fi

for file in $version_files; do
	tags="$(cat "$file")"
	release="$(basename "$file")"
	build="${BUILD_PREFIX}${release}"
	master="$(echo "$PREFIXES" | cut -d' ' -f1):master"

	: "${build:?}" "${tags:?}" "${release:?}"
  for tag in $tags; do
		for prefix in $PREFIXES; do
      docker push "${prefix}:${tag}"
    done
  done
done
